# Generated by Django 5.0.6 on 2024-06-03 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_year", models.IntegerField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="company_images/")),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=15)),
                ("founder", models.CharField(max_length=255)),
                ("investment_round", models.CharField(max_length=255)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
