# Generated by Django 5.0.6 on 2024-06-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InvestMagnet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="name",
        ),
    ]
