# Generated by Django 4.1.4 on 2024-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LifestyleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anxiety_level", models.FloatField()),
                ("mental_health_history", models.FloatField()),
                ("depression", models.FloatField()),
                ("headache", models.FloatField()),
                ("sleep_quality", models.FloatField()),
                ("safety", models.FloatField()),
                ("academic_performance", models.FloatField()),
                ("future_career_concerns", models.FloatField()),
                ("social_support", models.FloatField()),
                ("peer_pressure", models.FloatField()),
                ("extracurricular_activities", models.FloatField()),
                ("bullying", models.FloatField()),
                ("prediction", models.CharField(max_length=100)),
            ],
        ),
    ]
