# Generated by Django 5.0.6 on 2024-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentalHealth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive", models.IntegerField(default=0)),
                ("neutral", models.IntegerField(default=0)),
                ("negative", models.IntegerField(default=0)),
            ],
        ),
    ]
